app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'UserController@index');


Route::auth();

Route::get('/home', 'HomeController@index')->name('homepage');

Route::auth();

Route::get('/home', 'HomeController@index');

Route::get('redirect', function()
{
    if(Entrust::hasRole('admin')) {
    return redirect()->route('admin.dashboard');
    } else if(Entrust::hasRole('owner') ) {
    return redirect()->route('owner.dashboard');
    } else if(Entrust::hasRole('employee') ) {
        return redirect()->route('employee.articles.index');
    }  else {
        return redirect()->route('homepage');
    }
});

Route::group(['namespace' => 'owner', 'prefix' => 'owner', 'middleware' => ['role:owner']], function () {
    Route::get('edit-newspaper-info', 'DashboardController@editInfo')->name('owner.edit-newspaper-info');
    Route::post('edit-info', 'DashboardController@editInfoPost')->name('owner.edit-info');
    Route::get('dashboard', 'DashboardController@index')->name('owner.dashboard');
    Route::get('hire', 'DashboardController@hire')->name('owner.hire');
    Route::post('owner.hire-new', 'DashboardController@hireNew')->name('owner.hire-new');
    Route::post('fire-user', 'DashboardController@fireUser')->name('owner.fire-user');
    Route::post('articles.approve', 'ArticlesController@approve')->name('owner.articles.approve');
    Route::resource('articles', 'ArticlesController');

});

Route::group(['namespace' => 'admin', 'prefix' => 'admin', 'middleware' => ['role:admin']], function () {
    Route::get('dashboard', [ 'uses' => 'DashboardController@index', 'as' => 'admin.dashboard']);
    Route::resource('users', 'DashboardController', ['except' => ['create', 'store', 'edit', 'update']]);
    Route::resource('newspapers', 'NewspapersController');
});

Route::group(['namespace' => 'employee', 'prefix' => 'employee', 'middleware' => ['role:employee']], function () {
    Route::resource('articles', 'ArticlesController');
});

app/Models/Newspaper.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Newspaper extends Model
{
    //
}

app/Http/Controllers/Admin/NewspapersController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\Newspaper;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\NewspaperEmployee;
use Illuminate\Support\Facades\DB;

use App\Http\Requests;

class NewspapersController extends Controller
{
    public function index()
    {
        $newspapers = Newspaper::join('users', 'newspapers.user_id', '=', 'users.id')
                 ->selectRaw('newspapers.*, users.name as user_name, users.surname as user_surname')
                 ->paginate(10);

        return view('admin.newspapers.index', ['newspapers' => $newspapers, 'activeMenu' => 'newspapers']);
    }

    public function create()
    {
        $users = User::where('hired', 0)->get();

        return view('admin.newspapers.create', ['users' => $users, 'activeMenu' => 'newspapers']);
    }

    public function store(Request $request)
    {
        $newspaper = new Newspaper();
        $newspaper->newspapers_name = $request->input('name');
        $newspaper->user_id = $request->input('owner');
        $file = $request->file('image');

        $extension = $file->getClientOriginalExtension();
        $filename = microtime()*10000 . $newspaper->newspapers_name . '.' . $extension;
        $file->move('images/newspapers', $filename);
        $newspaper->img_url = $filename;
        $newspaper->save();
        $user = User::find($request->input('owner'));
        $user->hired = 1;
        $user->update();
        return redirect()->route('admin.newspapers.index');
    }

    public function edit($id)
    {
        $newspaper = Newspaper::find($id);
        $users = NewspaperEmployee::join('users', 'users.id', '=', 'newspaper_employees.user_id')
                                  ->where('newspaper_employees.newspaper_id', $id)
                                  ->selectRaw('users.*')
                                  ->get();
        $owner = User::find($newspaper->user_id);

        return view('admin.newspapers.edit', ['newspaper' => $newspaper, 'users' => $users, 'owner' => $owner, 'activeMenu' => 'newspapers']);
    }

    public function update($id, Request $request)
    {

        $newspaper = Newspaper::find($id);
        //Old boss gets fired

        $user = User::find($newspaper->user_id);
        $user->hired = 0;
        $user->type = 2;
        $user->update();
        //Change role from owner to user
        DB::table('role_user')->where('user_id', $user->id)->update(['role_id' => 4]);
        DB::table('role_user')->where('user_id', $request->input('owner'))->update(['role_id' => 2]);
        DB::table('newspaper_employees')->where('user_id', $request->input('owner'))->delete();
        DB::table('users')->where('id', $request->input('owner'))->update(['type' => 1, 'hired' => 1]);

        if($request->hasFile('image')) {
            unlink('images/newspapers/' . $newspaper->img_url);
            $file = $request->file('image');
            $extension = $file->getClientOriginalExtension();
            $filename = microtime()*10000 . $newspaper->newspapers_name . '.' . $extension;
            $file->move('images/newspapers', $filename);
            $newspaper->img_url = $filename;
        }
        $newspaper->newspapers_name = $request->input('name');
        $newspaper->user_id = $request->input('owner');
        $newspaper->save();
        return redirect()->route('admin.newspapers.index');
    }

    public function destroy($id)
    {
        Newspaper::where('id', $id)->delete();
        return redirect()->route('admin.newspapers.index');
    }
}

resources/views/admin/newspapers/create.blade.php
@extends('admin.layout')

@section('title')
    Create new Newspaper
@endsection

@section('head')
    <link href="{{ asset('assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css') }}" rel="stylesheet" type="text/css"/>
    <link href="{{ asset('css/general.css') }}" rel="stylesheet" type="text/css"/>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-6">
            <!-- BEGIN FORM-->
            <div class="portlet light bordered">
                <div class="portlet-body form">
                    <form method="post" action="{{ route('admin.newspapers.store') }}" class="newspapers-create-form" enctype="multipart/form-data">
                        <div class="form-body">
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" class="form-control input-circle" placeholder="Name" name="name" id="name" value="{{ old('name') }}">
                            </div>
                            <div class="form-group">
                                <label for="owner">Owner</label>
                                <select class="selectpicker form-control" name="owner" id="type">
                                    <option value="">Please choose...</option>
                                    @foreach($users as $user)
                                        <option value="{{ $user->id }}" @if (old('owner') == $user->id) selected @endif> {{ $user->username }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Image</label> <br>
                                <div data-provides="fileinput" class="fileinput fileinput-new">
                                    <div class="input-group input-large">
                                        <div data-trigger="fileinput" class="form-control uneditable-input input-fixed input-medium">
                                            <i class="fa fa-file fileinput-exists"></i>&nbsp;
                                            <span class="fileinput-filename"> </span>
                                        </div>

                                        <span class="input-group-addon btn default btn-file">
                                            <span class="fileinput-new">  Select image  </span>
                                            <span class="fileinput-exists"> Change </span>
                                            <input type="file" name="image"> <br>
                                        </span>
                                        <a data-dismiss="fileinput" class="input-group-addon btn purple fileinput-exists" href="javascript:;"> Remove </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button class="btn blue" type="submit">Create</button>
                            <a class="btn blue btn-outline sbold upppercase" href="{{ route('admin.newspapers.index') }}"> Cancel </a>
                        </div>
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    </form>
                </div>
            </div>
            <!-- END FORM-->
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('assets/global/plugins/jquery-validation/js/jquery.validate.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js') }}" type="text/javascript"></script>
    <script src="{{ asset('js/newspapers.js') }}" type="text/javascript"></script>
@endsection

resources/views/admin/newspapers/edit.blade.php
@extends('admin.layout')

@section('title')
    Edit {{ $newspaper->newspapers_name }} Newspaper
@endsection

@section('head')
    <link href="{{ asset('assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css') }}" rel="stylesheet" type="text/css"/>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-6">
            <!-- BEGIN FORM-->
            <div class="portlet light bordered">
                <div class="portlet-body form">
                    <form method="post" action="{{ route('admin.newspapers.update', $newspaper->id) }}" class="account-form" enctype="multipart/form-data">
                        <div class="form-body">
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" class="form-control input-circle" placeholder="Name" name="name" id="name" value="{{ old('name', $newspaper->newspapers_name) }}">
                            </div>
                            <div class="form-group">
                                <label for="owner">Owner</label>
                                <select class="selectpicker form-control" name="owner" id="type">
                                    <option value="">Please choose...</option>
                                    <option value="{{  $owner->id }}" @if (old('owner_id', $newspaper->user_id) ==  $owner->id) selected @endif> {{  $owner->username }}</option>
                                    @foreach($users as $user)
                                        <option value="{{ $user->id }}" @if (old('owner_id', $newspaper->user_id) == $user->id) selected @endif> {{ $user->username }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Image</label> <br>
                            <div data-provides="fileinput" class="fileinput fileinput-new">
                                <div>
                                    <img src="{{ asset('images/newspapers/'.$newspaper->img_url) }}" style="width: 300px; height: 100px;" />
                                </div>
                                <div class="input-group input-large">
                                    <div data-trigger="fileinput" class="form-control uneditable-input input-fixed input-medium">
                                        <i class="fa fa-file fileinput-exists"></i>&nbsp;
                                        <span class="fileinput-filename"> </span>
                                    </div>
                                        <span class="input-group-addon btn default btn-file">
                                            <span class="fileinput-new">  Select image  </span>
                                            <span class="fileinput-exists"> Change </span>
                                            <input type="file" name="image">
                                        </span>
                                    <a data-dismiss="fileinput" class="input-group-addon btn purple fileinput-exists" href="javascript:;"> Remove </a>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button class="btn blue" type="submit">Edit</button>
                            <a class="btn blue btn-outline sbold upppercase" href="{{ route('admin.newspapers.index') }}"> Cancel </a>
                        </div>
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <input type="hidden" name="_method" value="PUT">
                    </form>
                </div>
            </div>
            <!-- END FORM-->
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('assets/global/plugins/jquery-validation/js/jquery.validate.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js') }}" type="text/javascript"></script>
@endsection

resources/views/admin/newspapers/index.blade.php
@extends('admin.layout')
@section('title')
    Newspapers
@endsection
@section('content')
    <div class="row">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="actions">
                    <div class="btn-group">
                        <a class="btn blue  sbold upppercase" href="{{ route('admin.newspapers.create') }}"> Add New Newspaper </a>
                    </div>
                </div>
            </div>
            <div class="portlet-body">

                <div class="table-scrollable">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                        <tr>
                            <th scope="col"> Image </th>
                            <th scope="col"> Name </th>
                            <th scope="col"> Owner </th>
                            <th scope="col"> Actions </th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($newspapers as $newspaper)
                            <tr>
                                <td> <img src="{{ asset('images/newspapers/' . $newspaper->img_url) }}" style="height: 100px;"/> </td>
                                <td> {{ $newspaper->newspapers_name }} </td>
                                <td> {{ $newspaper->user_name }} &nbsp; {{ $newspaper->user_surname }} </td>
                                <td>
                                    <div class="actions">
                                        <a data-trigger="hover" href="{{ route('admin.newspapers.edit', [$newspaper->id]) }}" class="btn btn-circle btn-icon-only btn-default tooltips " data-original-title="Edit Newspaper">
                                            <i class="fa fa-trash-o"></i>
                                        </a>
                                        <a data-trigger="hover" href="#deleteModal" class="btn btn-circle btn-icon-only btn-default tooltips icon-delete" data-original-title="Delete Newspaper" data-toggle="modal">
                                            <i class="fa fa-trash-o"></i>
                                        </a>
                                        <form method="post" action="{{ route('admin.newspapers.destroy', [$newspaper->id]) }}">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input type="hidden" name="_method" value="DELETE">
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                {{ $newspapers->render() }}
            </div>
            <!-- END SAMPLE TABLE PORTLET-->
        </div>
    </div>
    @include('admin.index-delete-modal', ['notion' => 'Newspaper'])
@endsection

@section('scripts')
    <script src="{{ asset('js/general.js') }}" type="text/javascript"></script>
@endsection