app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'UserController@index');


Route::auth();

Route::get('/home', 'HomeController@index')->name('homepage');

Route::auth();

Route::get('/home', 'HomeController@index');

Route::get('redirect', function()
{
    if(Entrust::hasRole('admin')) {
    return redirect()->route('admin.dashboard');
    } else if(Entrust::hasRole('owner') ) {
    return redirect()->route('owner.dashboard');
    } else if(Entrust::hasRole('employee') ) {
        return redirect()->route('employee.articles.index');
    }  else {
        return redirect()->route('homepage');
    }
});

Route::group(['namespace' => 'owner', 'prefix' => 'owner', 'middleware' => ['role:owner']], function () {
    Route::get('edit-newspaper-info', 'DashboardController@editInfo')->name('owner.edit-newspaper-info');
    Route::post('edit-info', 'DashboardController@editInfoPost')->name('owner.edit-info');
    Route::get('dashboard', 'DashboardController@index')->name('owner.dashboard');
    Route::get('hire', 'DashboardController@hire')->name('owner.hire');
    Route::post('owner.hire-new', 'DashboardController@hireNew')->name('owner.hire-new');
    Route::post('fire-user', 'DashboardController@fireUser')->name('owner.fire-user');
    Route::post('articles.approve', 'ArticlesController@approve')->name('owner.articles.approve');
    Route::resource('articles', 'ArticlesController');

});

Route::group(['namespace' => 'admin', 'prefix' => 'admin', 'middleware' => ['role:admin']], function () {
    Route::get('dashboard', [ 'uses' => 'DashboardController@index', 'as' => 'admin.dashboard']);
    Route::resource('users', 'DashboardController', ['except' => ['create', 'store', 'edit', 'update']]);
    Route::resource('newspapers', 'NewspapersController');
});

Route::group(['namespace' => 'employee', 'prefix' => 'employee', 'middleware' => ['role:employee']], function () {
    Route::resource('articles', 'ArticlesController');
});

resources/views/admin/dashboard.blade.php
@extends('admin.layout')
@section('title')
    All Users
@endsection
@section('content')
    <div class="row">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="actions">
                    <div class="btn-group">
                    </div>
                </div>
            </div>
            <div class="portlet-body">

                    <div class="table-scrollable">
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                            <tr>
                                <th scope="col"> Username </th>
                                <th scope="col"> E-mail </th>
                                <th scope="col"> Role </th>
                                <th scope="col"> Actions </th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($users as $user)
                                <tr>
                                    <td> {{ $user->username }} </td>
                                    <td> {{ $user->email }} </td>
                                    <td> {{ $user->getUserType($user->type) }} </td>
                                    <td>
                                        <div class="actions">
                                            <a data-trigger="hover" href="#deleteModal" class="btn btn-circle btn-icon-only btn-default tooltips icon-delete" data-original-title="Delete User" data-toggle="modal">
                                                <i class="fa fa-trash-o"></i>
                                            </a>
                                            <form method="post" action="{{ route('admin.users.destroy', [$user->id]) }}">
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                <input type="hidden" name="_method" value="DELETE">
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                {{ $users->render() }}
            </div>
            <!-- END SAMPLE TABLE PORTLET-->
        </div>
    </div>
    @include('admin.index-delete-modal', ['notion' => 'User'])
@endsection

@section('scripts')
    <script src="{{ asset('js/general.js') }}" type="text/javascript"></script>
@endsection

resources/views/admin/index-delete-modal.blade.php
<div id="deleteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Warning</h4>
            </div>
            <div class="modal-body">
                <p> Are you sure you want to delete {{ $notion }}? </p>
            </div>
            <div class="modal-footer">
                <a class="btn blue btn-outline sbold upppercase modal-cancel-delete-btn" href="#" data-dismiss="modal"> Cancel </a>
                <button class="btn blue modal-delete-btn" type="submit">Delete</button>
            </div>
        </div>
    </div>
</div>

resources/views/admin/layout.blade.php
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8" />
    <title>@yield('title') - ReadMe</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/global/plugins/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css"/>
    <link href="{{ asset('assets/global/plugins/simple-line-icons/simple-line-icons.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/global/plugins/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/global/plugins/uniform/css/uniform.default.css') }}" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->
    <link href="{{ asset('assets/global/plugins/bootstrap-select/css/bootstrap-select.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- BEGIN THEME GLOBAL STYLES -->
    <link href="{{ asset('assets/global/css/components.min.css') }}" rel="stylesheet" id="style_components" type="text/css" />
    <link href="{{ asset('assets/global/css/plugins.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- END THEME GLOBAL STYLES -->
    <!-- BEGIN THEME LAYOUT STYLES -->
    <link href="{{ asset('assets/layouts/layout/css/layout.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/layouts/layout/css/themes/darkblue.min.css') }}" rel="stylesheet" type="text/css" id="style_color" />
    <!-- END THEME LAYOUT STYLES -->
    <!-- BEGIN CUSTOM LAYOUT STYLES -->
    <link href="{{ asset('styles/admin/style.css') }}" rel="stylesheet" type="text/css" />
    <!-- END CUSTOM LAYOUT STYLES -->
    @yield('head')
    <link rel="shortcut icon" href="{{ asset('uu-favicon.ico') }}" />
</head>
<!-- END HEAD -->

<body class="page-header-fixed page-sidebar-closed-hide-logo page-content-white ">
<!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top">
    <!-- BEGIN HEADER INNER -->
    <div class="page-header-inner ">
        <!-- BEGIN LOGO -->
        <div class="page-logo">
            <a href="{{ asset('insights.dashboard') }}">
                <img src="{{ asset('images/admin/logo.png') }}" width="110px" height="32.5px" alt="logo" class="logo-default"/> </a>
            <div class="menu-toggler sidebar-toggler"> </div>
        </div>
        <!-- END LOGO -->
        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"> </a>
        <!-- END RESPONSIVE MENU TOGGLER -->
        <!-- BEGIN TOP NAVIGATION MENU -->
        <div class="top-menu">
            <div class="log-out">
                <a href="{{ url('/logout') }}">
                    <i class="fa fa-key"></i>
                    Log Out
                </a>
            </div>
        </div>
        <!-- END TOP NAVIGATION MENU -->
    </div>
    <!-- END HEADER INNER -->
</div>
<!-- END HEADER -->
<!-- BEGIN HEADER & CONTENT DIVIDER -->
<div class="clearfix"> </div>
<!-- END HEADER & CONTENT DIVIDER -->
<!-- BEGIN CONTAINER -->
<div class="page-container">
    <!-- BEGIN SIDEBAR -->
    <div class="page-sidebar-wrapper">
        <!-- BEGIN SIDEBAR -->
        <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
        <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
        <div class="page-sidebar navbar-collapse collapse">
            <!-- BEGIN SIDEBAR MENU -->
            <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
            <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
            <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
            <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
            <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
            <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
            <ul class="page-sidebar-menu  page-header-fixed" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" style="padding-top: 20px">
                <!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
                <li class="sidebar-toggler-wrapper hide">
                    <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
                    <div class="sidebar-toggler"> </div>
                    <!-- END SIDEBAR TOGGLER BUTTON -->
                </li>
                <li class="nav-item start @if (!empty($activeMenu)) @if ($activeMenu == 'dashboard') active @endif @endif">
                    <a class="nav-link" href="{{ route('admin.dashboard') }}">
                        <i class="fa fa-dashboard"></i>
                        <span class="title">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item start @if (!empty($activeMenu)) @if ($activeMenu == 'newspapers') active @endif @endif">
                    <a class="nav-link" href="{{ route('admin.newspapers.index') }}">
                        <i class="fa fa-dashboard"></i>
                        <span class="title">Newspapaers</span>
                    </a>
                </li>
                {{--<li class="nav-item @if ($activeMenu == 'contact-support') active @endif">
                    <a class="nav-link" href="{{ route('insights.contact-support') }}">
                        <i class="fa fa-support"></i>
                        <span class="title">Contact Support</span>
                    </a>
                </li>--}}
            </ul>
            <!-- END SIDEBAR MENU -->
            <!-- END SIDEBAR MENU -->
        </div>
        <!-- END SIDEBAR -->
    </div>
    <!-- END SIDEBAR -->
    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <!-- BEGIN CONTENT BODY -->
        <div class="page-content">
            <h3 class="page-title">
                @yield('title')
            </h3>
            @yield('content')
        </div>
        <!-- END CONTENT BODY -->
    </div>
    <!-- END CONTENT -->

</div>
<!-- END CONTAINER -->
<!-- BEGIN FOOTER -->
<div class="page-footer">
    <div class="page-footer-inner"> {{ date('Y') }} &copy; <a href="{{ route('homepage') }}" target="_blank">ReadMe.</a> Sva prava zadržana.
    </div>
    <div class="scroll-to-top">
        <i class="fa fa-arrow-circle-o-up"></i>
    </div>
</div>
<!-- END FOOTER -->
<!--[if lt IE 9]>
<script src="{{ asset('assets/global/plugins/respond.min.js') }}"></script>
<script src="{{ asset('assets/global/plugins/excanvas.min.js') }}"></script>
<![endif]-->
<!-- BEGIN CORE PLUGINS -->
<script src="{{ asset('assets/global/plugins/jquery.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/global/plugins/jquery-ui/jquery-ui.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/global/plugins/bootstrap/js/bootstrap.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/global/plugins/js.cookie.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/global/plugins/jquery.blockui.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/global/plugins/uniform/jquery.uniform.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/global/plugins/bootstrap-select/js/bootstrap-select.min.js') }}" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN THEME GLOBAL SCRIPTS -->
<script src="{{ asset('assets/global/scripts/app.min.js') }}" type="text/javascript"></script>
<!-- END THEME GLOBAL SCRIPTS -->
<!-- BEGIN THEME LAYOUT SCRIPTS -->
<script src="{{ asset('assets/layouts/layout/scripts/layout.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/layouts/layout/scripts/demo.min.js') }}" type="text/javascript"></script>
<!-- END THEME LAYOUT SCRIPTS -->
@yield('scripts')
<script src="{{ asset('scripts/admin/bundle.min.js') }}" type="text/javascript"></script>
</body>

</html>