app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'UserController@index');


Route::auth();

Route::get('/home', 'HomeController@index')->name('homepage');

Route::auth();

Route::get('/home', 'HomeController@index');

Route::get('redirect', function()
{
    if(Entrust::hasRole('admin')) {
    return redirect()->route('admin.dashboard');
    } else if(Entrust::hasRole('owner') ) {
    return redirect()->route('owner.dashboard');
    } else if(Entrust::hasRole('employee') ) {
        return redirect()->route('employee.articles.index');
    }  else {
        return redirect()->route('homepage');
    }
});

Route::group(['namespace' => 'owner', 'prefix' => 'owner', 'middleware' => ['role:owner']], function () {
    Route::get('edit-newspaper-info', 'DashboardController@editInfo')->name('owner.edit-newspaper-info');
    Route::post('edit-info', 'DashboardController@editInfoPost')->name('owner.edit-info');
    Route::get('dashboard', 'DashboardController@index')->name('owner.dashboard');
    Route::get('hire', 'DashboardController@hire')->name('owner.hire');
    Route::post('owner.hire-new', 'DashboardController@hireNew')->name('owner.hire-new');
    Route::post('fire-user', 'DashboardController@fireUser')->name('owner.fire-user');
    Route::post('articles.approve', 'ArticlesController@approve')->name('owner.articles.approve');
    Route::resource('articles', 'ArticlesController');

});

Route::group(['namespace' => 'admin', 'prefix' => 'admin', 'middleware' => ['role:admin']], function () {
    Route::get('dashboard', [ 'uses' => 'DashboardController@index', 'as' => 'admin.dashboard']);
    Route::resource('users', 'DashboardController', ['except' => ['create', 'store', 'edit', 'update']]);
    Route::resource('newspapers', 'NewspapersController');
});

Route::group(['namespace' => 'employee', 'prefix' => 'employee', 'middleware' => ['role:employee']], function () {
    Route::resource('articles', 'ArticlesController');
});

app/Http/Controllers/Employee/ArticlesController.php
<?php

namespace App\Http\Controllers\Employee;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Models\NewspaperArticle;
use App\Models\Newspaper;
use App\Models\NewspaperEmployee;
use Illuminate\Http\Request;
use App\Http\Requests;

class ArticlesController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        $articles = NewspaperArticle::where('user_id', $user->id)
                                    ->where('approved', 1)
                                    ->paginate(10);

        return view('employee.articles.index', ['articles' => $articles, 'activeMenu' => 'articles']);
    }

    public function create()
    {
        return view('employee.articles.create');
    }

    public function show($id)
    {
        $article = NewspaperArticle::find($id);
        return view('employee.articles.show', ['article' => $article, 'activeMenu' => 'articles']);
    }

    public function store(Request $request)
    {
        $user = Auth::user();
        $employee = NewspaperEmployee::where('user_id', $user->id)->first();
        $newspaper = Newspaper::where('id', $employee->newspaper_id)->first();
        $article =  new NewspaperArticle();
        $article->title = $request->input('title');
        $article->content = $request->input('content');
        $article->approved = 0;
        $file = $request->file('image');

        $extension = $file->getClientOriginalExtension();
        $filename = microtime()*10000 . $article->name . '.' . $extension;
        $file->move('images/articles', $filename);
        $article->img_url = $filename;

        $article->user_id = $user->id;
        $article->newspaper_id = $newspaper->id;
        $article->save();
        return redirect()->route('employee.articles.index');
    }

    public function edit($id)
    {
        $article = NewspaperArticle::find($id);
        return view('employee.articles.edit', ['article' => $article, 'activeMenu' => 'articles']);
    }

    public function update(Request $request, $id)
    {
        $article = NewspaperArticle::find($id);
        $article->title = $request->input('title');
        $article->content = $request->input('content');
        //TODO update picture
        $article->update();
        return redirect()->route('employee.articles.index');
    }
}

app/Http/Controllers/Owner/ArticlesController.php
<?php

namespace App\Http\Controllers\Owner;

use App\Http\Controllers\Controller;
use App\Models\NewspaperArticle;
use App\Models\Newspaper;
use Illuminate\Http\Request;
use App\Http\Requests;
use Illuminate\Support\Facades\Auth;

class ArticlesController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        $newspaper = Newspaper::where('user_id', $user->id)->first();
        $articles = NewspaperArticle::join('users', 'users.id', '=', 'newspaper_articles.user_id')
                                    ->selectRaw('newspaper_articles.*, users.username as username')
                                    ->where('newspaper_id', $newspaper->id)
                                    ->where('approved', 1)
                                    ->paginate(10);
        $pendingArticles = NewspaperArticle::join('users', 'users.id', '=', 'newspaper_articles.user_id')
            ->selectRaw('newspaper_articles.*, users.username as username')
            ->where('newspaper_id', $newspaper->id)
            ->where('approved', 0)
            ->paginate(10);

        return view('owner.articles.index', ['articles' => $articles, 'pendingArticles' => $pendingArticles, 'activeMenu' => 'articles']);
    }

    public function create()
    {
        return view('owner.articles.create');
    }

    public function show($id)
    {
        $article = NewspaperArticle::find($id);
        return view('owner.articles.show', ['article' => $article, 'activeMenu' => 'articles']);
    }

    public function store(Request $request)
    {
        $user = Auth::user();
        $newspaper = Newspaper::where('user_id', $user->id)->first();
        $article =  new NewspaperArticle();
        $article->title = $request->input('title');
        $article->content = $request->input('content');
        $article->approved = 1;
        //TODO UPLOAD PICTURE
        $article->user_id = $user->id;
        $article->newspaper_id = $newspaper->id;
        $article->save();
        return redirect()->route('owner.articles.index');
    }

    public function approve(Request $request)
    {
        $article = NewspaperArticle::find($request->input('id'));
        $article->approved = 1;
        $article->save();
        return redirect()->route('owner.articles.index');
    }

    public function edit($id)
    {
        $article = NewspaperArticle::find($id);
        return view('owner.articles.edit', ['article' => $article, 'activeMenu' => 'articles']);
    }

    public function update(Request $request, $id)
    {
        $article = NewspaperArticle::find($id);
        $article->title = $request->input('title');
        $article->content = $request->input('content');
        //TODO update picture
        $article->update();
        return redirect()->route('owner.articles.index');
    }

    public function destroy($id)
    {
        NewspaperArticle::where('id', $id)->delete();
        return redirect()->route('owner.articles.index');
    }


}

resources/views/employee/articles/create.blade.php
@extends('employee.layout')
@section('title')
    Create new Article
@endsection

@section('head')
    <link href="{{ asset('assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css') }}" rel="stylesheet" type="text/css"/>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-6">
            <!-- BEGIN FORM-->
            <div class="portlet light bordered">
                <div class="portlet-body form">
                    <form method="post" action="{{ route('employee.articles.store') }}" class="account-form" enctype="multipart/form-data">
                        <div class="form-body">
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text" class="form-control input-circle" placeholder="Name" name="title" id="title" value="{{ old('title') }}">
                            </div>
                            <div class="form-group">
                                <label for="content">Content</label>
                                <textarea rows="10" class="form-control" name="content" id="content">{{ old('content') }}</textarea>
                            </div>
                            <div class="form-group">
                                <label>Image</label> <br>
                                <div data-provides="fileinput" class="fileinput fileinput-new">
                                    <div class="input-group input-large">
                                        <div data-trigger="fileinput" class="form-control uneditable-input input-fixed input-medium">
                                            <i class="fa fa-file fileinput-exists"></i>&nbsp;
                                            <span class="fileinput-filename"> </span>
                                        </div>
                                        <span class="input-group-addon btn default btn-file">
                                            <span class="fileinput-new">  Select image  </span>
                                            <span class="fileinput-exists"> Change </span>
                                            <input type="file" name="image">
                                        </span>
                                        <a data-dismiss="fileinput" class="input-group-addon btn purple fileinput-exists" href="javascript:;"> Remove </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button class="btn blue" type="submit">Create</button>
                            <a class="btn blue btn-outline sbold upppercase" href="{{ route('employee.articles.index') }}"> Cancel </a>
                        </div>
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    </form>
                </div>
            </div>
            <!-- END FORM-->
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('assets/global/plugins/jquery-validation/js/jquery.validate.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js') }}" type="text/javascript"></script>
@endsection

resources/views/employee/articles/edit.blade.php
@extends('employee.layout')
@section('title')
    Edit {{ $article->title }} Article
@endsection
@section('content')
    <div class="row">
        <div class="col-md-6">
            <!-- BEGIN FORM-->
            <div class="portlet light bordered">
                <div class="portlet-body form">
                    <form method="post" action="{{ route('employee.articles.update', [ $article->id ]) }}" class="account-form">
                        <div class="form-body">
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text" class="form-control input-circle" placeholder="Title" name="title" id="title" value="{{ old('title', $article->title) }}">
                            </div>
                            <div class="form-group">
                                <label for="content">Content</label>
                                <textarea rows="10" class="form-control" name="content" id="content">{{ old('content', $article->content) }}</textarea>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button class="btn blue" type="submit">Edit</button>
                            <a class="btn blue btn-outline sbold upppercase" href="{{ route('employee.articles.index') }}"> Cancel </a>
                        </div>
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <input type="hidden" name="_method" value="PUT">
                    </form>
                </div>
            </div>
            <!-- END FORM-->
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('admin-assets/global/plugins/jquery-validation/js/jquery.validate.min.js') }}" type="text/javascript"></script>
@endsection

resources/views/employee/articles/index.blade.php
@extends('employee.layout')
@section('title')
    Articles
@endsection
@section('content')
    <div class="row">
        <div class="portlet box blue">
            <div class="portlet-title">
                <h3>Approved Articles</h3>
                <div class="actions">
                    <div class="btn-group">
                        <a class="btn blue  sbold upppercase" href="{{ route('employee.articles.create') }}"> Add New Article </a>
                    </div>
                </div>
            </div>
            <div class="portlet-body">

                <div class="table-scrollable">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                        <tr>
                            <th scope="col"> Title </th>
                            <th scope="col"> Actions </th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($articles as $article)
                            <tr>
                                <td> <a href="{{ route('employee.articles.show', [$article->id]) }}">{{ $article->title }}</a> </td>
                                <td>
                                    <div class="actions">
                                        <a data-trigger="hover" href="{{ route('employee.articles.edit', [$article->id]) }}" class="btn btn-circle btn-icon-only btn-default tooltips " data-original-title="Edit Article">
                                            <i class="fa fa-trash-o"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                {{ $articles->render() }}
            </div>
            <!-- END SAMPLE TABLE PORTLET-->
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('js/general.js') }}" type="text/javascript"></script>
@endsection

resources/views/employee/articles/show.blade.php
@extends('employee.layout')

@section('content')
<div class="row">
    <div class="col-md-6">
        <!-- BEGIN FORM-->
        <div class="portlet light bordered">
            <div class="portlet-body form">
                <form role="form">
                    <div class="form-body">
                        <div class="form-group">
                            <label>Title</label>
                            <label class="form-control input-circle"> {{ $article->title }} </label>
                        </div>
                        <div class="form-group">
                            <label>Content</label>
                            <textarea rows="10" class="form-control readonly-element" readonly>{{ $article->content }}</textarea>
                        </div>
                    </div>
                    <div class="form-actions">
                        <a class="btn blue btn-outline sbold upppercase" href="{{ route('employee.articles.edit', [$article->id]) }}"> Edit </a>
                        <a class="btn blue btn-outline sbold upppercase " href="{{ route('employee.articles.index') }}" data-toggle="modal"> Back </a>
                    </div>
                </form>
            </div>
        </div>
        <!-- END FORM-->
    </div>
</div>
@endsection