app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'UserController@index');


Route::auth();

Route::get('/home', 'HomeController@index')->name('homepage');

Route::auth();

Route::get('/home', 'HomeController@index');

Route::get('redirect', function()
{
    if(Entrust::hasRole('admin')) {
    return redirect()->route('admin.dashboard');
    } else if(Entrust::hasRole('owner') ) {
    return redirect()->route('owner.dashboard');
    } else if(Entrust::hasRole('employee') ) {
        return redirect()->route('employee.articles.index');
    }  else {
        return redirect()->route('homepage');
    }
});

Route::group(['namespace' => 'owner', 'prefix' => 'owner', 'middleware' => ['role:owner']], function () {
    Route::get('edit-newspaper-info', 'DashboardController@editInfo')->name('owner.edit-newspaper-info');
    Route::post('edit-info', 'DashboardController@editInfoPost')->name('owner.edit-info');
    Route::get('dashboard', 'DashboardController@index')->name('owner.dashboard');
    Route::get('hire', 'DashboardController@hire')->name('owner.hire');
    Route::post('owner.hire-new', 'DashboardController@hireNew')->name('owner.hire-new');
    Route::post('fire-user', 'DashboardController@fireUser')->name('owner.fire-user');
    Route::post('articles.approve', 'ArticlesController@approve')->name('owner.articles.approve');
    Route::resource('articles', 'ArticlesController');

});

Route::group(['namespace' => 'admin', 'prefix' => 'admin', 'middleware' => ['role:admin']], function () {
    Route::get('dashboard', [ 'uses' => 'DashboardController@index', 'as' => 'admin.dashboard']);
    Route::resource('users', 'DashboardController', ['except' => ['create', 'store', 'edit', 'update']]);
    Route::resource('newspapers', 'NewspapersController');
});

Route::group(['namespace' => 'employee', 'prefix' => 'employee', 'middleware' => ['role:employee']], function () {
    Route::resource('articles', 'ArticlesController');
});

app/Http/Controllers/Employee/ArticlesController.php
<?php

namespace App\Http\Controllers\Employee;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Models\NewspaperArticle;
use App\Models\Newspaper;
use App\Models\NewspaperEmployee;
use Illuminate\Http\Request;
use App\Http\Requests;

class ArticlesController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        $articles = NewspaperArticle::where('user_id', $user->id)
                                    ->where('approved', 1)
                                    ->paginate(10);

        return view('employee.articles.index', ['articles' => $articles, 'activeMenu' => 'articles']);
    }

    public function create()
    {
        return view('employee.articles.create');
    }

    public function show($id)
    {
        $article = NewspaperArticle::find($id);
        return view('employee.articles.show', ['article' => $article, 'activeMenu' => 'articles']);
    }

    public function store(Request $request)
    {
        $user = Auth::user();
        $employee = NewspaperEmployee::where('user_id', $user->id)->first();
        $newspaper = Newspaper::where('id', $employee->newspaper_id)->first();
        $article =  new NewspaperArticle();
        $article->title = $request->input('title');
        $article->content = $request->input('content');
        $article->approved = 0;
        $file = $request->file('image');

        $extension = $file->getClientOriginalExtension();
        $filename = microtime()*10000 . $article->name . '.' . $extension;
        $file->move('images/articles', $filename);
        $article->img_url = $filename;

        $article->user_id = $user->id;
        $article->newspaper_id = $newspaper->id;
        $article->save();
        return redirect()->route('employee.articles.index');
    }

    public function edit($id)
    {
        $article = NewspaperArticle::find($id);
        return view('employee.articles.edit', ['article' => $article, 'activeMenu' => 'articles']);
    }

    public function update(Request $request, $id)
    {
        $article = NewspaperArticle::find($id);
        $article->title = $request->input('title');
        $article->content = $request->input('content');
        //TODO update picture
        $article->update();
        return redirect()->route('employee.articles.index');
    }
}

app/Http/Controllers/Owner/ArticlesController.php
<?php

namespace App\Http\Controllers\Owner;

use App\Http\Controllers\Controller;
use App\Models\NewspaperArticle;
use App\Models\Newspaper;
use Illuminate\Http\Request;
use App\Http\Requests;
use Illuminate\Support\Facades\Auth;

class ArticlesController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        $newspaper = Newspaper::where('user_id', $user->id)->first();
        $articles = NewspaperArticle::join('users', 'users.id', '=', 'newspaper_articles.user_id')
                                    ->selectRaw('newspaper_articles.*, users.username as username')
                                    ->where('newspaper_id', $newspaper->id)
                                    ->where('approved', 1)
                                    ->paginate(10);
        $pendingArticles = NewspaperArticle::join('users', 'users.id', '=', 'newspaper_articles.user_id')
            ->selectRaw('newspaper_articles.*, users.username as username')
            ->where('newspaper_id', $newspaper->id)
            ->where('approved', 0)
            ->paginate(10);

        return view('owner.articles.index', ['articles' => $articles, 'pendingArticles' => $pendingArticles, 'activeMenu' => 'articles']);
    }

    public function create()
    {
        return view('owner.articles.create');
    }

    public function show($id)
    {
        $article = NewspaperArticle::find($id);
        return view('owner.articles.show', ['article' => $article, 'activeMenu' => 'articles']);
    }

    public function store(Request $request)
    {
        $user = Auth::user();
        $newspaper = Newspaper::where('user_id', $user->id)->first();
        $article =  new NewspaperArticle();
        $article->title = $request->input('title');
        $article->content = $request->input('content');
        $article->approved = 1;
        //TODO UPLOAD PICTURE
        $article->user_id = $user->id;
        $article->newspaper_id = $newspaper->id;
        $article->save();
        return redirect()->route('owner.articles.index');
    }

    public function approve(Request $request)
    {
        $article = NewspaperArticle::find($request->input('id'));
        $article->approved = 1;
        $article->save();
        return redirect()->route('owner.articles.index');
    }

    public function edit($id)
    {
        $article = NewspaperArticle::find($id);
        return view('owner.articles.edit', ['article' => $article, 'activeMenu' => 'articles']);
    }

    public function update(Request $request, $id)
    {
        $article = NewspaperArticle::find($id);
        $article->title = $request->input('title');
        $article->content = $request->input('content');
        //TODO update picture
        $article->update();
        return redirect()->route('owner.articles.index');
    }

    public function destroy($id)
    {
        NewspaperArticle::where('id', $id)->delete();
        return redirect()->route('owner.articles.index');
    }


}

app/Http/Controllers/Owner/DashboardController.php
<?php

namespace App\Http\Controllers\Owner;


use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\NewspaperEmployee;
use App\Models\Newspaper;
use App\Models\User;
use App\Role;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class DashboardController extends Controller
{
    //
    public function index()
    {
        $owner = Auth::user();

        $newspaper = Newspaper::where('user_id', $owner->id)->first();
        $employees = NewspaperEmployee::where('newspaper_id', $newspaper->id)->get();
        $ids = [];
        foreach($employees as $employee)
        {
            array_push($ids, $employee->user_id);
        }
        $users = User::whereIn('id', $ids)->get();
        return view('owner.dashboard', ['users' => $users, 'newspaper' => $newspaper, 'activeMenu' => 'dashboard']);
    }

    public function editInfo()
    {
        $owner = Auth::user();

        $newspaper = Newspaper::where('user_id', $owner->id)->first();

        return view('owner.edit-info', ['newspaper' => $newspaper, 'activeMenu' => 'dashboard']);
    }

    public function hire()
    {
        $users = User::where('hired', 0)->get();
        return view('owner.hire', ['users' => $users, 'activeMenu' => 'dashboard']);
    }

    public function hireNew(Request $request)
    {
        $owner = Auth::user();
        $newspaper = Newspaper::where('user_id', $owner->id)->first();
        $employee = new NewspaperEmployee();
        $employee->user_id = $request->input('user_id');
        $employee->newspaper_id = $newspaper->id;
        $employee->save();
        DB::table('role_user')->where('user_id', $request->input('user_id'))->update(['role_id' => 3]);
        return redirect()->route('owner.dashboard');
    }

    public function fireUser(Request $request)
    {
        NewspaperEmployee::where('user_id', $request->input('id'))->delete();
        $user = User::find($request->input('id'));
        $user->hired = 0;
        $user->save();
        DB::table('role_user')->where('user_id', $request->input('id'))->update(['role_id' => 4]);
        return redirect()->route('owner.dashboard');
    }

    public function editInfoPost(Request $request)
    {
        $newspaper = Newspaper::find($request->input('id'));
        $newspaper->newspapers_name = $request->input('name');
        $newspaper->save();
        //TODO CHANGE PICTURE
        return redirect()->route('owner.dashboard');
    }

}

resources/views/owner/articles/create.blade.php
@extends('owner.layout')
@section('title')
    Create new Article
@endsection
@section('content')
    <div class="row">
        <div class="col-md-6">
            <!-- BEGIN FORM-->
            <div class="portlet light bordered">
                <div class="portlet-body form">
                    <form method="post" action="{{ route('owner.articles.store') }}" class="account-form">
                        <div class="form-body">
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text" class="form-control input-circle" placeholder="Name" name="title" id="title" value="{{ old('title') }}">
                            </div>
                            <div class="form-group">
                                <label for="content">Content</label>
                                <textarea rows="10" class="form-control" name="content" id="content">{{ old('content') }}</textarea>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button class="btn blue" type="submit">Create</button>
                            <a class="btn blue btn-outline sbold upppercase" href="{{ route('owner.articles.index') }}"> Cancel </a>
                        </div>
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    </form>
                </div>
            </div>
            <!-- END FORM-->
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('admin-assets/global/plugins/jquery-validation/js/jquery.validate.min.js') }}" type="text/javascript"></script>
@endsection

resources/views/owner/articles/edit.blade.php
@extends('owner.layout')
@section('title')
    Edit {{ $article->title }} Article
@endsection
@section('content')
    <div class="row">
        <div class="col-md-6">
            <!-- BEGIN FORM-->
            <div class="portlet light bordered">
                <div class="portlet-body form">
                    <form method="post" action="{{ route('owner.articles.update', [ $article->id ]) }}" class="account-form">
                        <div class="form-body">
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text" class="form-control input-circle" placeholder="Title" name="title" id="title" value="{{ old('title', $article->title) }}">
                            </div>
                            <div class="form-group">
                                <label for="content">Content</label>
                                <textarea rows="10" class="form-control" name="content" id="content">{{ old('content', $article->content) }}</textarea>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button class="btn blue" type="submit">Edit</button>
                            <a class="btn blue btn-outline sbold upppercase" href="{{ route('owner.articles.index') }}"> Cancel </a>
                        </div>
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <input type="hidden" name="_method" value="PUT">
                    </form>
                </div>
            </div>
            <!-- END FORM-->
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('admin-assets/global/plugins/jquery-validation/js/jquery.validate.min.js') }}" type="text/javascript"></script>
@endsection

resources/views/owner/articles/index.blade.php
@extends('owner.layout')
@section('title')
    Articles
@endsection
@section('content')
    <div class="row">
        <div class="portlet box blue">
            <div class="portlet-title">
                <h3>Approved Articles</h3>
                <div class="actions">
                    <div class="btn-group">
                        <a class="btn blue  sbold upppercase" href="{{ route('owner.articles.create') }}"> Add New Article </a>
                    </div>
                </div>
            </div>
            <div class="portlet-body">

                <div class="table-scrollable">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                        <tr>
                            <th scope="col"> Title </th>
                            <th scope="col"> Author </th>
                            <th scope="col"> Actions </th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($articles as $article)
                            <tr>
                                <td> <a href="{{ route('owner.articles.show', [$article->id]) }}">{{ $article->title }}</a> </td>
                                <td> {{ $article->username }} </td>
                                <td>
                                    <div class="actions">
                                        <a data-trigger="hover" href="{{ route('owner.articles.edit', [$article->id]) }}" class="btn btn-circle btn-icon-only btn-default tooltips " data-original-title="Edit Article">
                                            <i class="fa fa-trash-o"></i>
                                        </a>
                                        <a data-trigger="hover" href="#deleteModal" class="btn btn-circle btn-icon-only btn-default tooltips icon-delete" data-original-title="Delete Article" data-toggle="modal">
                                            <i class="fa fa-trash-o"></i>
                                        </a>
                                        <form method="post" action="{{ route('owner.articles.destroy', [$article->id]) }}">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input type="hidden" name="_method" value="DELETE">
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                {{ $articles->render() }}
            </div>
            <!-- END SAMPLE TABLE PORTLET-->
        </div>
        <div class="portlet box blue">
            <div class="portlet-title">
                <h3>Pending Articles</h3>
            </div>
            <div class="portlet-body">

                <div class="table-scrollable">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                        <tr>
                            <th scope="col"> Title </th>
                            <th scope="col"> Author </th>
                            <th scope="col"> Actions </th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($pendingArticles as $pendingArticle)
                            <tr>
                                <td> <a href="{{ route('owner.articles.show', [$pendingArticle->id]) }}">{{ $pendingArticle->title }}</a> </td>
                                <td> {{ $pendingArticle->username }} </td>
                                <td>
                                    <div class="actions">
                                        <a data-trigger="hover" href="{{ route('owner.articles.edit', [$pendingArticle->id]) }}" class="btn btn-circle btn-icon-only btn-default tooltips " data-original-title="Edit Article">
                                            <i class="fa fa-trash-o"></i>
                                        </a>
                                        <form method="post" action="{{ route('owner.articles.approve') }}">
                                            <a data-trigger="hover" href="#" class="btn btn-circle btn-icon-only btn-default tooltips article-btns" data-original-title="Approve Article">
                                                <i class="fa fa-trash-o"></i>
                                            </a>
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input type="hidden" name="id" value="{{ $pendingArticle->id }}">
                                        </form><form method="post" action="{{ route('owner.articles.destroy', [$pendingArticle->id]) }}">
                                            <a data-trigger="hover" href="#" class="btn btn-circle btn-icon-only btn-default tooltips article-btns" data-original-title="Disapprove Article">
                                                <i class="fa fa-trash-o"></i>
                                            </a>
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input type="hidden" name="_method" value="DELETE">
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END SAMPLE TABLE PORTLET-->
        </div>
    </div>
    @include('admin.index-delete-modal', ['notion' => 'Article'])
@endsection

@section('scripts')
    <script src="{{ asset('js/general.js') }}" type="text/javascript"></script>
@endsection

resources/views/owner/articles/show.blade.php
@extends('owner.layout')

@section('content')
<div class="row">
    <div class="col-md-6">
        <!-- BEGIN FORM-->
        <div class="portlet light bordered">
            <div class="portlet-body form">
                <form role="form">
                    <div class="form-body">
                        <div class="form-group">
                            <label>Title</label>
                            <label class="form-control input-circle"> {{ $article->title }} </label>
                        </div>
                        <div class="form-group">
                            <label>Content</label>
                            <textarea rows="10" class="form-control readonly-element" readonly>{{ $article->content }}</textarea>
                        </div>
                    </div>
                    <div class="form-actions">
                        <a class="btn blue btn-outline sbold upppercase" href="{{ route('owner.articles.edit', [$article->id]) }}"> Edit </a>
                        <a class="btn blue btn-outline sbold upppercase " href="{{ route('owner.articles.index') }}" data-toggle="modal"> Back </a>
                    </div>
                </form>
            </div>
        </div>
        <!-- END FORM-->
    </div>
</div>
@endsection